included:

excluded:
  - Pods
  - Cartography
  - build
  - Permanent/EnvVars.stencil
  - Permanent/EnvVars.generated.swift

disabled_rules:
  - duplicate_enum_cases
  - empty_enum_arguments
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - inclusive_language
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - private_over_fileprivate
  - trailing_whitespace
  - type_body_length
  - unused_closure_parameter
  - unused_enumerated
  - void_return
  
opt_in_rules:
  - closure_end_indentation
  - closure_body_length
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - indentation_width
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - operator_usage_whitespace
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unused_declaration
  - unused_import
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - file_header
  
identifier_name:
  min_length:
    warning: 2
    error: 1
unused_declaration: 
  severity: warning
empty_count: 
  severity: warning
vertical_whitespace: 
  severity: error
vertical_whitespace_closing_braces: 
  severity: error
vertical_whitespace_opening_braces: 
  severity: error
closure_body_length:
  warning: 80
  error: 120
file_header:
  severity: error
  required_pattern: |
                    \/\/( *?)
                    \/\/.*?\.swift
                    \/\/( *?)(Permanent.*?)
                    \/\/( *?)
                    \/\/( *?)Created by .*? on .*?
                    \/\/( *?)
