#!/bin/sh
# Fills Permanent/App/EnvVars.generated.swift: every {{ argument.x }} in the stencil becomes the
# matching environment variable. Replaces the Sourcery pod, whose binary ran on Intel only.
set -eu

ROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
TEMPLATE="${ROOT}/Permanent/App/EnvVars.stencil"
OUTPUT="${ROOT}/Permanent/App/EnvVars.generated.swift"

# A local env file wins on a developer Mac; CI exports the same variables as secrets.
if [ -n "${ENV_VARS_FILENAME:-}" ] && [ -f "${ROOT}/${ENV_VARS_FILENAME}" ]; then
  # shellcheck disable=SC1090
  . "${ROOT}/${ENV_VARS_FILENAME}"
fi

# Secrets and env files may wrap a value in quotes, as '123' or "'123'"; every layer is dropped.
unquote() {
  value=$1
  while :; do
    case $value in
      \"*\") value=${value#\"}; value=${value%\"} ;;
      \'*\') value=${value#\'}; value=${value%\'} ;;
      *) break ;;
    esac
  done
  printf '%s' "$value"
}

# Unquotes a value and escapes the characters sed treats specially inside a replacement.
esc() { unquote "$1" | sed -e 's/[\\&|]/\\&/g'; }

{
  echo "// Generated by Scripts/generate-env-vars.sh from EnvVars.stencil. Do not edit."
  sed -e "s|{{ argument.clientId }}|$(esc "${CLIENT_ID:-}")|g" \
      -e "s|{{ argument.reversedClientId }}|$(esc "${REVERSED_CLIENT_ID:-}")|g" \
      -e "s|{{ argument.apiKey }}|$(esc "${API_KEY:-}")|g" \
      -e "s|{{ argument.gcmSenderId }}|$(esc "${GCM_SENDER_ID:-}")|g" \
      -e "s|{{ argument.projectId }}|$(esc "${PROJECT_ID:-}")|g" \
      -e "s|{{ argument.storageBucket }}|$(esc "${STORAGE_BUCKET:-}")|g" \
      -e "s|{{ argument.googleAppId }}|$(esc "${GOOGLE_APP_ID:-}")|g" \
      -e "s|{{ argument.authClientId }}|$(esc "${AUTH_CLIENT_ID:-}")|g" \
      -e "s|{{ argument.authClientSecret }}|$(esc "${AUTH_CLIENT_SECRET:-}")|g" \
      -e "s|{{ argument.authTenantId }}|$(esc "${AUTH_TENANT_ID:-}")|g" \
      -e "s|{{ argument.authFusionAuthorization }}|$(esc "${AUTH_FUSION_AUTHORIZATION:-}")|g" \
      -e "s|{{ argument.stripePublishableKey }}|$(esc "${STRIPE_PUB_KEY:-}")|g" \
      -e "s|{{ argument.uiTestUsername }}|$(esc "${UI_TEST_USERNAME:-}")|g" \
      -e "s|{{ argument.uiTestPassword }}|$(esc "${UI_TEST_PASSWORD:-}")|g" \
      -e "s|{{ argument.mixpanelToken }}|$(esc "${MIXPANEL_TOKEN:-}")|g" \
      "$TEMPLATE"
} > "${OUTPUT}.tmp"

# Only touch the output when a value changed, so plain rebuilds stay incremental.
if cmp -s "${OUTPUT}.tmp" "$OUTPUT"; then
  rm -f "${OUTPUT}.tmp"
else
  mv "${OUTPUT}.tmp" "$OUTPUT"
fi
