name: Deploy Firebase Beta

on:
  workflow_dispatch:
  push:
    branches: [ "Development" ]

jobs:
  build:
    name: Build and deploy a beta build to Firebase Distribution
    runs-on: self-hosted
    environment: staging

    steps:
      - name: Clean Working directory
        uses: AutoModality/action-clean@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Bundler
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '2.6.8'
          bundler-cache: true
      - name: Run Fastlane Beta
        env:
          CLIENT_ID: ${{ secrets.IOS_FIREBASE_CLIENT_ID }}
          REVERSED_CLIENT_ID: ${{ secrets.IOS_FIREBASE_REVERSED_CLIENT_ID }}
          API_KEY: ${{ secrets.IOS_FIREBASE_API_KEY }}
          GCM_SENDER_ID: ${{ secrets.IOS_FIREBASE_GCM_SENDER_ID }}
          PROJECT_ID: ${{ secrets.IOS_FIREBASE_PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.IOS_FIREBASE_STORAGE_BUCKET }}
          GOOGLE_APP_ID: ${{ secrets.IOS_FIREBASE_GOOGLE_APP_ID }}
          AUTH_TENANT_ID: ${{ secrets.MOBILE_AUTH_TENANT_ID }}
          AUTH_CLIENT_ID: ${{ secrets.MOBILE_AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.MOBILE_AUTH_CLIENT_SECRET }}
          STRIPE_PUB_KEY: ${{ secrets.MOBILE_STRIPE_TEST_PUB_KEY }}
          UI_TEST_USERNAME: ${{ secrets.IOS_UI_TEST_USERNAME }}
          UI_TEST_PASSWORD: ${{ secrets.IOS_UI_TEST_PASSWORD }}
          SKIPLINT: true
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          FIREBASEAPPDISTRO_APP: ${{ secrets.IOS_FIREBASE_GOOGLE_APP_ID }}
          FIREBASEAPPDISTRO_GROUPS: ${{ secrets.IOS_FIREBASE_APP_DISTRIBUTION_GROUPS }}
          FIREBASE_TOKEN: ${{ secrets.IOS_FIREBASE_APP_CLI_TOKEN }}
          FASTLANE_MATCH_TOKEN: ${{ secrets.FASTLANE_MATCH_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: bundle exec fastlane beta
