name: PR Automated tests

on:
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Bundler
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '2.6'
          bundler-cache: true
      - name: Run Fastlane Tests
        run: bundle exec fastlane tests
