name: PR Automated tests

on:
  workflow_dispatch:
    inputs:
      test_plan:
        description: 'TestPlan to run'
        required: true
        default: 'unit-tests'
        type: choice
        options:
        - unit-tests
        - ui-tests
        - all-tests
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Bundler
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: '2.6.8'
          bundler-cache: true
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run Fastlane Tests
        env:
          CLIENT_ID: ${{ secrets.IOS_FIREBASE_CLIENT_ID }}
          REVERSED_CLIENT_ID: ${{ secrets.IOS_FIREBASE_REVERSED_CLIENT_ID }}
          API_KEY: ${{ secrets.IOS_FIREBASE_API_KEY }}
          GCM_SENDER_ID: ${{ secrets.IOS_FIREBASE_GCM_SENDER_ID }}
          PROJECT_ID: ${{ secrets.IOS_FIREBASE_PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.IOS_FIREBASE_STORAGE_BUCKET }}
          GOOGLE_APP_ID: ${{ secrets.IOS_FIREBASE_GOOGLE_APP_ID }}
          AUTH_TENANT_ID: ${{ secrets.MOBILE_AUTH_TENANT_ID }}
          AUTH_CLIENT_ID: ${{ secrets.MOBILE_AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.MOBILE_AUTH_CLIENT_SECRET }}
          STRIPE_PUB_KEY: ${{ secrets.MOBILE_STRIPE_TEST_PUB_KEY }}
          UI_TEST_USERNAME: ${{ secrets.IOS_UI_TEST_USERNAME }}
          UI_TEST_PASSWORD: ${{ secrets.IOS_UI_TEST_PASSWORD }}
          SKIPLINT: true
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          FIREBASEAPPDISTRO_APP: ${{ secrets.IOS_FIREBASE_GOOGLE_APP_ID }}
          FIREBASEAPPDISTRO_GROUPS: ${{ secrets.IOS_FIREBASE_APP_DISTRIBUTION_GROUPS }}
          FIREBASEAPPDISTRO_CLI_TOKEN: ${{ secrets.IOS_FIREBASE_APP_CLI_TOKEN }}
          TEST_PLAN: 'unit-tests'
        run: bundle exec fastlane tests
